- name: Install and Start Cloudflare WARP
        run: |
          # Добавляем репозиторий Cloudflare
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list

          # Устанавливаем warp-cli
          sudo apt-get update && sudo apt-get install -y cloudflare-warp

          # Регистрируем и подключаем клиент
          warp-cli --accept-tos registration new
          warp-cli --accept-tos mode warp
          warp-cli --accept-tos connect

          # Ждем поднятия туннеля и проверяем новый IP
          sleep 3
          echo "Current IP via WARP:"
          curl -s https://cloudflare.com/cdn-cgi/trace | grep ip
