name: YouTube to GDrive Pipeline

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_pipeline]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt

      - name: Run downloader script
        env:
          EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_SERVICE_KEY: ${{ secrets.GDRIVE_SERVICE_KEY }}
          CF_WORKER_URL: ${{ secrets.CF_WORKER_URL }}
        run: python main.py
